version: '3.1'
services:
    mariadb:
        image: 'mariadb:10.6'
        working_dir: /docker-entrypoint-initdb.d
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_DATABASE=heap_overload
            - MYSQL_USER=alex
            - MYSQL_PASSWORD=admin
        ports:
            - '8003:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'

    php-fpm:
        build: docker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/php-fpm/php-fpm-ini-overrides.ini:/etc/php-fpm/8.2/fpm/conf.d/99-overrides.ini'